// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ssh_coreFFI)
import ssh_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ssh_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ssh_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSshCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol SshSessionHandleProtocol: AnyObject, Sendable {
    
    /**
     * Establishes the SSH connection, launches tmux, and starts streaming I/O.
     */
    func connect(callback: SshSessionCallback) throws 
    
    /**
     * Zero Battery Drain: gracefully closes the SSH channel and TCP socket.
     * tmux continues running remote agent tasks detached on the MacBook.
     */
    func disconnect() 
    
    /**
     * Instant reconnection on app foreground (didBecomeActive).
     * Re-attaches to the existing detached tmux session.
     */
    func reconnect() throws 
    
    /**
     * Dynamically resizes the remote terminal viewport (triggers remote SIGWINCH in tmux).
     */
    func resize(cols: UInt16, rows: UInt16) throws 
    
    /**
     * Sends raw user keystrokes / input bytes to the remote terminal.
     */
    func sendInput(data: Data) throws 
    
    /**
     * Returns current state.
     */
    func state()  -> SessionState
    
}
open class SshSessionHandle: SshSessionHandleProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_ssh_core_fn_clone_sshsessionhandle(self.handle, $0) }
    }
public convenience init(config: SessionConfig) {
    let handle =
        try! rustCall() {
        uniffiCallStatus in
    uniffi_ssh_core_fn_constructor_sshsessionhandle_new(
        FfiConverterTypeSessionConfig_lower(config),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_ssh_core_fn_free_sshsessionhandle(handle, $0) }
    }

    

    
    /**
     * Establishes the SSH connection, launches tmux, and starts streaming I/O.
     */
open func connect(callback: SshSessionCallback)throws   {try rustCallWithError(FfiConverterTypeSshCoreError_lift) {
        uniffiCallStatus in
    uniffi_ssh_core_fn_method_sshsessionhandle_connect(
            self.uniffiCloneHandle(),
        FfiConverterCallbackInterfaceSshSessionCallback_lower(callback),uniffiCallStatus
    )
}
}
    
    /**
     * Zero Battery Drain: gracefully closes the SSH channel and TCP socket.
     * tmux continues running remote agent tasks detached on the MacBook.
     */
open func disconnect()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_ssh_core_fn_method_sshsessionhandle_disconnect(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
    /**
     * Instant reconnection on app foreground (didBecomeActive).
     * Re-attaches to the existing detached tmux session.
     */
open func reconnect()throws   {try rustCallWithError(FfiConverterTypeSshCoreError_lift) {
        uniffiCallStatus in
    uniffi_ssh_core_fn_method_sshsessionhandle_reconnect(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
    /**
     * Dynamically resizes the remote terminal viewport (triggers remote SIGWINCH in tmux).
     */
open func resize(cols: UInt16, rows: UInt16)throws   {try rustCallWithError(FfiConverterTypeSshCoreError_lift) {
        uniffiCallStatus in
    uniffi_ssh_core_fn_method_sshsessionhandle_resize(
            self.uniffiCloneHandle(),
        FfiConverterUInt16.lower(cols),
        FfiConverterUInt16.lower(rows),uniffiCallStatus
    )
}
}
    
    /**
     * Sends raw user keystrokes / input bytes to the remote terminal.
     */
open func sendInput(data: Data)throws   {try rustCallWithError(FfiConverterTypeSshCoreError_lift) {
        uniffiCallStatus in
    uniffi_ssh_core_fn_method_sshsessionhandle_send_input(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(data),uniffiCallStatus
    )
}
}
    
    /**
     * Returns current state.
     */
open func state() -> SessionState  {
    return try!  FfiConverterTypeSessionState_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_ssh_core_fn_method_sshsessionhandle_state(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSshSessionHandle: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SshSessionHandle

    public static func lift(_ handle: UInt64) throws -> SshSessionHandle {
        return SshSessionHandle(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SshSessionHandle) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SshSessionHandle {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SshSessionHandle, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSshSessionHandle_lift(_ handle: UInt64) throws -> SshSessionHandle {
    return try FfiConverterTypeSshSessionHandle.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSshSessionHandle_lower(_ value: SshSessionHandle) -> UInt64 {
    return FfiConverterTypeSshSessionHandle.lower(value)
}




/**
 * Canonical signing payload representation for agent approvals.
 */
public struct CanonicalSigningPayload: Equatable, Hashable {
    public var id: String
    public var commandHashSha256: String
    public var nonce: String
    public var timestampSec: UInt64
    public var approved: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, commandHashSha256: String, nonce: String, timestampSec: UInt64, approved: Bool) {
        self.id = id
        self.commandHashSha256 = commandHashSha256
        self.nonce = nonce
        self.timestampSec = timestampSec
        self.approved = approved
    }

    

    
}

#if compiler(>=6)
extension CanonicalSigningPayload: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCanonicalSigningPayload: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CanonicalSigningPayload {
        return
            try CanonicalSigningPayload(
                id: FfiConverterString.read(from: &buf), 
                commandHashSha256: FfiConverterString.read(from: &buf), 
                nonce: FfiConverterString.read(from: &buf), 
                timestampSec: FfiConverterUInt64.read(from: &buf), 
                approved: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: CanonicalSigningPayload, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.commandHashSha256, into: &buf)
        FfiConverterString.write(value.nonce, into: &buf)
        FfiConverterUInt64.write(value.timestampSec, into: &buf)
        FfiConverterBool.write(value.approved, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCanonicalSigningPayload_lift(_ buf: RustBuffer) throws -> CanonicalSigningPayload {
    return try FfiConverterTypeCanonicalSigningPayload.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCanonicalSigningPayload_lower(_ value: CanonicalSigningPayload) -> RustBuffer {
    return FfiConverterTypeCanonicalSigningPayload.lower(value)
}


public struct KeypairResult: Equatable, Hashable {
    public var publicKeyOpenssh: String
    public var privateKeyOpenssh: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(publicKeyOpenssh: String, privateKeyOpenssh: String) {
        self.publicKeyOpenssh = publicKeyOpenssh
        self.privateKeyOpenssh = privateKeyOpenssh
    }

    

    
}

#if compiler(>=6)
extension KeypairResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKeypairResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KeypairResult {
        return
            try KeypairResult(
                publicKeyOpenssh: FfiConverterString.read(from: &buf), 
                privateKeyOpenssh: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: KeypairResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.publicKeyOpenssh, into: &buf)
        FfiConverterString.write(value.privateKeyOpenssh, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeypairResult_lift(_ buf: RustBuffer) throws -> KeypairResult {
    return try FfiConverterTypeKeypairResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeypairResult_lower(_ value: KeypairResult) -> RustBuffer {
    return FfiConverterTypeKeypairResult.lower(value)
}


public struct RemoteServerConfig: Equatable, Hashable {
    public var host: String
    public var port: UInt16
    public var username: String
    public var privateKeyPem: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(host: String, port: UInt16, username: String, privateKeyPem: String) {
        self.host = host
        self.port = port
        self.username = username
        self.privateKeyPem = privateKeyPem
    }

    

    
}

#if compiler(>=6)
extension RemoteServerConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRemoteServerConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RemoteServerConfig {
        return
            try RemoteServerConfig(
                host: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf), 
                username: FfiConverterString.read(from: &buf), 
                privateKeyPem: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RemoteServerConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.host, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
        FfiConverterString.write(value.username, into: &buf)
        FfiConverterString.write(value.privateKeyPem, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRemoteServerConfig_lift(_ buf: RustBuffer) throws -> RemoteServerConfig {
    return try FfiConverterTypeRemoteServerConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRemoteServerConfig_lower(_ value: RemoteServerConfig) -> RustBuffer {
    return FfiConverterTypeRemoteServerConfig.lower(value)
}


public struct SessionConfig: Equatable, Hashable {
    public var host: String
    public var port: UInt16
    public var username: String
    public var privateKeyPem: String
    public var sessionName: String
    public var initialCols: UInt16
    public var initialRows: UInt16
    public var command: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(host: String, port: UInt16, username: String, privateKeyPem: String, sessionName: String, initialCols: UInt16, initialRows: UInt16, command: String?) {
        self.host = host
        self.port = port
        self.username = username
        self.privateKeyPem = privateKeyPem
        self.sessionName = sessionName
        self.initialCols = initialCols
        self.initialRows = initialRows
        self.command = command
    }

    

    
}

#if compiler(>=6)
extension SessionConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionConfig {
        return
            try SessionConfig(
                host: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf), 
                username: FfiConverterString.read(from: &buf), 
                privateKeyPem: FfiConverterString.read(from: &buf), 
                sessionName: FfiConverterString.read(from: &buf), 
                initialCols: FfiConverterUInt16.read(from: &buf), 
                initialRows: FfiConverterUInt16.read(from: &buf), 
                command: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SessionConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.host, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
        FfiConverterString.write(value.username, into: &buf)
        FfiConverterString.write(value.privateKeyPem, into: &buf)
        FfiConverterString.write(value.sessionName, into: &buf)
        FfiConverterUInt16.write(value.initialCols, into: &buf)
        FfiConverterUInt16.write(value.initialRows, into: &buf)
        FfiConverterOptionString.write(value.command, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionConfig_lift(_ buf: RustBuffer) throws -> SessionConfig {
    return try FfiConverterTypeSessionConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionConfig_lower(_ value: SessionConfig) -> RustBuffer {
    return FfiConverterTypeSessionConfig.lower(value)
}


public struct TerminalSize: Equatable, Hashable {
    public var cols: UInt16
    public var rows: UInt16

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(cols: UInt16, rows: UInt16) {
        self.cols = cols
        self.rows = rows
    }

    

    
}

#if compiler(>=6)
extension TerminalSize: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTerminalSize: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TerminalSize {
        return
            try TerminalSize(
                cols: FfiConverterUInt16.read(from: &buf), 
                rows: FfiConverterUInt16.read(from: &buf)
        )
    }

    public static func write(_ value: TerminalSize, into buf: inout [UInt8]) {
        FfiConverterUInt16.write(value.cols, into: &buf)
        FfiConverterUInt16.write(value.rows, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTerminalSize_lift(_ buf: RustBuffer) throws -> TerminalSize {
    return try FfiConverterTypeTerminalSize.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTerminalSize_lower(_ value: TerminalSize) -> RustBuffer {
    return FfiConverterTypeTerminalSize.lower(value)
}


/**
 * Structured information about an active remote tmux session.
 */
public struct TmuxSessionInfo: Equatable, Hashable {
    public var name: String
    public var windows: UInt32
    public var attached: Bool
    public var createdTimestamp: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, windows: UInt32, attached: Bool, createdTimestamp: UInt64) {
        self.name = name
        self.windows = windows
        self.attached = attached
        self.createdTimestamp = createdTimestamp
    }

    

    
}

#if compiler(>=6)
extension TmuxSessionInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTmuxSessionInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TmuxSessionInfo {
        return
            try TmuxSessionInfo(
                name: FfiConverterString.read(from: &buf), 
                windows: FfiConverterUInt32.read(from: &buf), 
                attached: FfiConverterBool.read(from: &buf), 
                createdTimestamp: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TmuxSessionInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt32.write(value.windows, into: &buf)
        FfiConverterBool.write(value.attached, into: &buf)
        FfiConverterUInt64.write(value.createdTimestamp, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTmuxSessionInfo_lift(_ buf: RustBuffer) throws -> TmuxSessionInfo {
    return try FfiConverterTypeTmuxSessionInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTmuxSessionInfo_lower(_ value: TmuxSessionInfo) -> RustBuffer {
    return FfiConverterTypeTmuxSessionInfo.lower(value)
}



public enum SessionState: Equatable, Hashable {
    
    case disconnected
    case connecting
    case connected
    case reconnecting
    case failed(reason: String
    )





}

#if compiler(>=6)
extension SessionState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionState: FfiConverterRustBuffer {
    typealias SwiftType = SessionState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .disconnected
        
        case 2: return .connecting
        
        case 3: return .connected
        
        case 4: return .reconnecting
        
        case 5: return .failed(reason: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SessionState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .disconnected:
            writeInt(&buf, Int32(1))
        
        
        case .connecting:
            writeInt(&buf, Int32(2))
        
        
        case .connected:
            writeInt(&buf, Int32(3))
        
        
        case .reconnecting:
            writeInt(&buf, Int32(4))
        
        
        case let .failed(reason):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionState_lift(_ buf: RustBuffer) throws -> SessionState {
    return try FfiConverterTypeSessionState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionState_lower(_ value: SessionState) -> RustBuffer {
    return FfiConverterTypeSessionState.lower(value)
}



public 
enum SshCoreError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case KeyGenerationError(reason: String
    )
    case KeyParseError(reason: String
    )
    case InvalidSessionName(name: String, reason: String
    )
    case ConnectionError(reason: String
    )
    case AuthenticationError(username: String, reason: String
    )
    case ChannelError(reason: String
    )
    case IoError(reason: String
    )
    case AlreadyConnected
    case NotConnected
    case Timeout
    case ApprovalVerificationError(reason: String
    )
    case InvalidApprovalPayload(reason: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SshCoreError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSshCoreError: FfiConverterRustBuffer {
    typealias SwiftType = SshCoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SshCoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .KeyGenerationError(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .KeyParseError(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidSessionName(
            name: try FfiConverterString.read(from: &buf), 
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .ConnectionError(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 5: return .AuthenticationError(
            username: try FfiConverterString.read(from: &buf), 
            reason: try FfiConverterString.read(from: &buf)
            )
        case 6: return .ChannelError(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 7: return .IoError(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 8: return .AlreadyConnected
        case 9: return .NotConnected
        case 10: return .Timeout
        case 11: return .ApprovalVerificationError(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 12: return .InvalidApprovalPayload(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SshCoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .KeyGenerationError(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .KeyParseError(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .InvalidSessionName(name,reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(name, into: &buf)
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .ConnectionError(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .AuthenticationError(username,reason):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(username, into: &buf)
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .ChannelError(reason):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .IoError(reason):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .AlreadyConnected:
            writeInt(&buf, Int32(8))
        
        
        case .NotConnected:
            writeInt(&buf, Int32(9))
        
        
        case .Timeout:
            writeInt(&buf, Int32(10))
        
        
        case let .ApprovalVerificationError(reason):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .InvalidApprovalPayload(reason):
            writeInt(&buf, Int32(12))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSshCoreError_lift(_ buf: RustBuffer) throws -> SshCoreError {
    return try FfiConverterTypeSshCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSshCoreError_lower(_ value: SshCoreError) -> RustBuffer {
    return FfiConverterTypeSshCoreError.lower(value)
}




public protocol SshSessionCallback: AnyObject, Sendable {
    
    func onStateChanged(state: SessionState) 
    
    func onDataReceived(data: Data) 
    
    func onError(message: String) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceSshSessionCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceSshSessionCallback = UniffiVTableCallbackInterfaceSshSessionCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceSshSessionCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface SshSessionCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceSshSessionCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface SshSessionCallback: handle missing in uniffiClone")
            }
        },
        onStateChanged: { (
            uniffiHandle: UInt64,
            state: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSshSessionCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onStateChanged(
                     state: try FfiConverterTypeSessionState_lift(state)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onDataReceived: { (
            uniffiHandle: UInt64,
            data: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSshSessionCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDataReceived(
                     data: try FfiConverterData.lift(data)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSshSessionCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onError(
                     message: try FfiConverterString.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceSshSessionCallback> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceSshSessionCallback>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitSshSessionCallback() {
    uniffi_ssh_core_fn_init_callback_vtable_sshsessioncallback(UniffiCallbackInterfaceSshSessionCallback.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceSshSessionCallback {
    fileprivate static let handleMap = UniffiHandleMap<SshSessionCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceSshSessionCallback : FfiConverter {
    typealias SwiftType = SshSessionCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSshSessionCallback_lift(_ handle: UInt64) throws -> SshSessionCallback {
    return try FfiConverterCallbackInterfaceSshSessionCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSshSessionCallback_lower(_ v: SshSessionCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceSshSessionCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTmuxSessionInfo: FfiConverterRustBuffer {
    typealias SwiftType = [TmuxSessionInfo]

    public static func write(_ value: [TmuxSessionInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTmuxSessionInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TmuxSessionInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [TmuxSessionInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTmuxSessionInfo.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureSshCoreInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func coreVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_ssh_core_fn_func_core_version(uniffiCallStatus
    )
})
}
public func generateSshKeypair()throws  -> KeypairResult  {
    return try  FfiConverterTypeKeypairResult_lift(try rustCallWithError(FfiConverterTypeSshCoreError_lift) {
        uniffiCallStatus in
    uniffi_ssh_core_fn_func_generate_ssh_keypair(uniffiCallStatus
    )
})
}
/**
 * Serializes approval data into canonical bytes for signing.
 */
public func createCanonicalSigningBytes(id: String, commandHashSha256: String, nonce: String, timestampSec: UInt64, approved: Bool) -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_ssh_core_fn_func_create_canonical_signing_bytes(
        FfiConverterString.lower(id),
        FfiConverterString.lower(commandHashSha256),
        FfiConverterString.lower(nonce),
        FfiConverterUInt64.lower(timestampSec),
        FfiConverterBool.lower(approved),uniffiCallStatus
    )
})
}
/**
 * Computes SHA256 hash of a command string formatted as lowercase hex.
 */
public func hashCommandSha256(command: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_ssh_core_fn_func_hash_command_sha256(
        FfiConverterString.lower(command),uniffiCallStatus
    )
})
}
/**
 * Verifies whether an approval decision's timestamp falls within the allowed tolerance window.
 */
public func verifyApprovalFreshness(timestampSec: UInt64, currentTimeSec: UInt64, maxDriftSec: UInt64) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_ssh_core_fn_func_verify_approval_freshness(
        FfiConverterUInt64.lower(timestampSec),
        FfiConverterUInt64.lower(currentTimeSec),
        FfiConverterUInt64.lower(maxDriftSec),uniffiCallStatus
    )
})
}
/**
 * Verifies an Ed25519 signature over canonical approval bytes against an OpenSSH public key.
 */
public func verifyApprovalSignature(publicKeyOpenssh: String, canonicalBytes: Data, signatureHex: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeSshCoreError_lift) {
        uniffiCallStatus in
    uniffi_ssh_core_fn_func_verify_approval_signature(
        FfiConverterString.lower(publicKeyOpenssh),
        FfiConverterData.lower(canonicalBytes),
        FfiConverterString.lower(signatureHex),uniffiCallStatus
    )
})
}
public func derivePublicKey(privateKeyOpenssh: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSshCoreError_lift) {
        uniffiCallStatus in
    uniffi_ssh_core_fn_func_derive_public_key(
        FfiConverterString.lower(privateKeyOpenssh),uniffiCallStatus
    )
})
}
public func executeRemoteCommand(config: RemoteServerConfig, command: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ssh_core_fn_func_execute_remote_command(FfiConverterTypeRemoteServerConfig_lower(config),FfiConverterString.lower(command)
                )
            },
            pollFunc: ffi_ssh_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_ssh_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_ssh_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeSshCoreError_lift
        )
}
public func killRemoteTmuxSession(config: RemoteServerConfig, sessionName: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ssh_core_fn_func_kill_remote_tmux_session(FfiConverterTypeRemoteServerConfig_lower(config),FfiConverterString.lower(sessionName)
                )
            },
            pollFunc: ffi_ssh_core_rust_future_poll_void,
            completeFunc: ffi_ssh_core_rust_future_complete_void,
            freeFunc: ffi_ssh_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeSshCoreError_lift
        )
}
public func listRemoteTmuxSessions(config: RemoteServerConfig)async throws  -> [TmuxSessionInfo]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ssh_core_fn_func_list_remote_tmux_sessions(FfiConverterTypeRemoteServerConfig_lower(config)
                )
            },
            pollFunc: ffi_ssh_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_ssh_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_ssh_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeTmuxSessionInfo.lift,
            errorHandler: FfiConverterTypeSshCoreError_lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ssh_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ssh_core_checksum_func_core_version() != 64561) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_func_generate_ssh_keypair() != 25495) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_func_create_canonical_signing_bytes() != 57755) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_func_hash_command_sha256() != 26218) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_func_verify_approval_freshness() != 26260) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_func_verify_approval_signature() != 51597) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_func_derive_public_key() != 26782) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_func_execute_remote_command() != 30132) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_func_kill_remote_tmux_session() != 45685) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_func_list_remote_tmux_sessions() != 48899) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_method_sshsessionhandle_connect() != 11069) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_method_sshsessionhandle_disconnect() != 50492) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_method_sshsessionhandle_reconnect() != 62860) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_method_sshsessionhandle_resize() != 24870) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_method_sshsessionhandle_send_input() != 51464) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_method_sshsessionhandle_state() != 27048) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_constructor_sshsessionhandle_new() != 21965) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_method_sshsessioncallback_on_state_changed() != 19101) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_method_sshsessioncallback_on_data_received() != 28278) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ssh_core_checksum_method_sshsessioncallback_on_error() != 55584) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitSshSessionCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSshCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all